# Generated by Django 5.1 on 2024-08-29 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='lastname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
