# Generated by Django 5.1 on 2024-08-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_rename_first_name_customuser_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='lastname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='tlp',
            field=models.CharField(default='', max_length=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
